# Railway Configuration for Palm Oil Management System
# This file configures deployment to Railway with Turso database

# Build Command
build:
  dockerfile: Dockerfile

# Environment Variables
env:
  - name: SECRET_KEY
    generateValue: true
  - name: GOOGLE_API_KEY
    prompt: "Enter your Google Gemini API Key"
  - name: TURSO_DATABASE_URL
    prompt: "Enter your Turso Database URL"
  - name: TURSO_AUTH_TOKEN
    prompt: "Enter your Turso Auth Token"
  - name: FLASK_DEBUG
    value: "false"

# Port Configuration
port: 5000

# Health Check
healthcheckPath: /health
healthcheckTimeout: 300
restartPolicyType: ON_FAILURE
restartPolicyMaxRetries: 10